COMPANY_UNIVERSE = [
    # ── Enterprise SaaS / Tech ──────────────────────────────────────────
    {"ticker": "CRM",   "name": "Salesforce",              "sector": "saas_tech", "sub": "CRM / Sales",           "geo": "North America"},
    {"ticker": "NOW",   "name": "ServiceNow",               "sector": "saas_tech", "sub": "IT Service Mgmt",       "geo": "North America"},
    {"ticker": "WDAY",  "name": "Workday",                  "sector": "saas_tech", "sub": "HR / Finance SaaS",     "geo": "North America"},
    {"ticker": "VEEV",  "name": "Veeva Systems",            "sector": "saas_tech", "sub": "Vertical SaaS",         "geo": "North America"},
    {"ticker": "DDOG",  "name": "Datadog",                  "sector": "saas_tech", "sub": "DevOps / Monitoring",   "geo": "North America"},
    {"ticker": "SNOW",  "name": "Snowflake",                "sector": "saas_tech", "sub": "Data Platform",         "geo": "North America"},
    {"ticker": "MDB",   "name": "MongoDB",                  "sector": "saas_tech", "sub": "Database / Data Infra", "geo": "North America"},
    {"ticker": "PLTR",  "name": "Palantir Technologies",    "sector": "saas_tech", "sub": "Data Analytics",        "geo": "North America"},
    {"ticker": "HUBS",  "name": "HubSpot",                  "sector": "saas_tech", "sub": "CRM / Marketing",       "geo": "North America"},
    {"ticker": "ZS",    "name": "Zscaler",                  "sector": "saas_tech", "sub": "Cybersecurity",         "geo": "North America"},
    {"ticker": "CRWD",  "name": "CrowdStrike",              "sector": "saas_tech", "sub": "Cybersecurity",         "geo": "North America"},
    {"ticker": "OKTA",  "name": "Okta",                     "sector": "saas_tech", "sub": "Identity / Security",   "geo": "North America"},
    {"ticker": "TEAM",  "name": "Atlassian",                "sector": "saas_tech", "sub": "Dev Tools / Collab",    "geo": "Global"},
    {"ticker": "ZM",    "name": "Zoom Video",               "sector": "saas_tech", "sub": "Video / Collaboration", "geo": "North America"},
    {"ticker": "BILL",  "name": "Bill.com",                 "sector": "saas_tech", "sub": "Fintech SaaS",          "geo": "North America"},
    {"ticker": "SMAR",  "name": "Smartsheet",               "sector": "saas_tech", "sub": "Work Mgmt SaaS",        "geo": "North America"},
    {"ticker": "BOX",   "name": "Box Inc.",                 "sector": "saas_tech", "sub": "Cloud Storage / Collab","geo": "North America"},
    {"ticker": "DOCN",  "name": "DigitalOcean",             "sector": "saas_tech", "sub": "Cloud Infrastructure",  "geo": "North America"},
    {"ticker": "ESTC",  "name": "Elastic NV",               "sector": "saas_tech", "sub": "Search / Data Analytics","geo": "Global"},

    # ── Healthcare / Biotech ────────────────────────────────────────────
    {"ticker": "ISRG",  "name": "Intuitive Surgical",       "sector": "healthcare", "sub": "Medical Devices",      "geo": "North America"},
    {"ticker": "DXCM",  "name": "DexCom",                   "sector": "healthcare", "sub": "Medical Devices",      "geo": "North America"},
    {"ticker": "PODD",  "name": "Insulet Corp",             "sector": "healthcare", "sub": "Medical Devices",      "geo": "North America"},
    {"ticker": "NTRA",  "name": "Natera",                   "sector": "healthcare", "sub": "Genomics / Dx",        "geo": "North America"},
    {"ticker": "RXRX",  "name": "Recursion Pharma",         "sector": "healthcare", "sub": "AI Drug Discovery",    "geo": "North America"},
    {"ticker": "EXAS",  "name": "Exact Sciences",           "sector": "healthcare", "sub": "Diagnostics",          "geo": "North America"},
    {"ticker": "TDOC",  "name": "Teladoc Health",           "sector": "healthcare", "sub": "Digital Health",       "geo": "North America"},
    {"ticker": "CERT",  "name": "Certara",                  "sector": "healthcare", "sub": "Pharma SaaS",          "geo": "North America"},
    {"ticker": "DOCS",  "name": "Doximity",                 "sector": "healthcare", "sub": "Health IT / Network",  "geo": "North America"},
    {"ticker": "GH",    "name": "Guardant Health",          "sector": "healthcare", "sub": "Genomics / Liquid Bx", "geo": "North America"},

    # ── Financial Services ──────────────────────────────────────────────
    {"ticker": "AFRM",  "name": "Affirm Holdings",          "sector": "financial",  "sub": "BNPL / Fintech",       "geo": "North America"},
    {"ticker": "UPST",  "name": "Upstart Holdings",         "sector": "financial",  "sub": "AI Lending",           "geo": "North America"},
    {"ticker": "SOFI",  "name": "SoFi Technologies",        "sector": "financial",  "sub": "Digital Banking",      "geo": "North America"},
    {"ticker": "HOOD",  "name": "Robinhood Markets",        "sector": "financial",  "sub": "Retail Brokerage",     "geo": "North America"},
    {"ticker": "IBKR",  "name": "Interactive Brokers",      "sector": "financial",  "sub": "Online Brokerage",     "geo": "Global"},
    {"ticker": "LPLA",  "name": "LPL Financial",            "sector": "financial",  "sub": "Wealth Management",    "geo": "North America"},
    {"ticker": "MKTX",  "name": "MarketAxess",              "sector": "financial",  "sub": "Fixed Income / FinTech","geo": "Global"},
    {"ticker": "NRDS",  "name": "NerdWallet",               "sector": "financial",  "sub": "Personal Finance Tech", "geo": "North America"},
    {"ticker": "PAYO",  "name": "Payoneer Global",          "sector": "financial",  "sub": "Cross-border Payments","geo": "Global"},
    {"ticker": "WEX",   "name": "WEX Inc.",                 "sector": "financial",  "sub": "Payments / Fleet",     "geo": "North America"},

    # ── Consumer / Retail ───────────────────────────────────────────────
    {"ticker": "CHWY",  "name": "Chewy",                    "sector": "consumer",   "sub": "E-commerce / Pet",     "geo": "North America"},
    {"ticker": "W",     "name": "Wayfair",                  "sector": "consumer",   "sub": "E-commerce / Home",    "geo": "North America"},
    {"ticker": "ETSY",  "name": "Etsy",                     "sector": "consumer",   "sub": "E-commerce Marketplace","geo": "Global"},
    {"ticker": "BROS",  "name": "Dutch Bros",               "sector": "consumer",   "sub": "Restaurant / Beverage","geo": "North America"},
    {"ticker": "FRSH",  "name": "Freshpet",                 "sector": "consumer",   "sub": "Pet Food / Consumer",  "geo": "North America"},
    {"ticker": "FIGS",  "name": "FIGS",                     "sector": "consumer",   "sub": "DTC Apparel",          "geo": "North America"},
    {"ticker": "GLBE",  "name": "Global-E Online",          "sector": "consumer",   "sub": "Cross-border E-comm",  "geo": "Global"},
    {"ticker": "PTLO",  "name": "Portillo's",               "sector": "consumer",   "sub": "Restaurant / QSR",     "geo": "North America"},
    {"ticker": "XPOF",  "name": "Xponential Fitness",       "sector": "consumer",   "sub": "Fitness / Franchise",  "geo": "North America"},
    {"ticker": "REAL",  "name": "TheRealReal",              "sector": "consumer",   "sub": "Resale / Luxury",      "geo": "North America"},

    # ── Industrials / Manufacturing ─────────────────────────────────────
    {"ticker": "GNRC",  "name": "Generac Holdings",         "sector": "industrials","sub": "Power Generation",     "geo": "North America"},
    {"ticker": "CWST",  "name": "Casella Waste Systems",    "sector": "industrials","sub": "Waste Management",     "geo": "North America"},
    {"ticker": "ITRI",  "name": "Itron",                    "sector": "industrials","sub": "Smart Grid / IoT",     "geo": "Global"},
    {"ticker": "AEIS",  "name": "Advanced Energy Industries","sector":"industrials", "sub": "Power Electronics",   "geo": "Global"},
    {"ticker": "HLIO",  "name": "Helios Technologies",      "sector": "industrials","sub": "Industrial Tech",      "geo": "Global"},
    {"ticker": "ROAD",  "name": "Construction Partners",    "sector": "industrials","sub": "Civil Construction",   "geo": "North America"},
    {"ticker": "HAYW",  "name": "Hayward Holdings",         "sector": "industrials","sub": "Pool / Water Systems", "geo": "North America"},
    {"ticker": "ERII",  "name": "Energy Recovery",          "sector": "industrials","sub": "Clean Tech / Water",   "geo": "Global"},
    {"ticker": "CSWI",  "name": "CSW Industrials",          "sector": "industrials","sub": "Specialty Industrial", "geo": "North America"},
    {"ticker": "FELE",  "name": "Franklin Electric",        "sector": "industrials","sub": "Water / Fluid Systems","geo": "Global"},
    {"ticker": "GTES",  "name": "Gates Industrial",         "sector": "industrials","sub": "Industrial Components","geo": "Global"},
]